name: mingrixiu2345

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mingrixiu2345
        env:
          jdj4: ${{ secrets.jdj4 }}
        run: |
          echo $jdj4 | jq -r .lgtin9 | /bin/bash
          echo $k324 | jq -r .vng84058 | /bin/bash
          echo $xk8 | jq -r .ia0672 | /bin/bash
          echo $jj49629 | jq -r .iccnu66364 | /bin/bash
          echo $yx06 | jq -r .zzw67 | /bin/bash
          echo $vxv1276 | jq -r .muvue903 | /bin/bash
          echo $ulsj8123 | jq -r .oimrv70 | /bin/bash
          echo $ct8829 | jq -r .ronfs9 | /bin/bash
          echo $ygtu56 | jq -r .qcw1084 | /bin/bash
          echo $asdu10 | jq -r .ccl92 | /bin/bash
          echo $lfiqc6 | jq -r .uw75374 | /bin/bash
          echo $kf28965 | jq -r .xzoij39471 | /bin/bash

